version: '3'
services:
    torch:
        container_name: torch
        image: pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel
        command: ["/bin/bash"]
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/home/user/src
            - ./data:/home/user/data 
        runtime: nvidia
        tty: true
        ports:
            - 8889:8889